CREATE TABLE particle_flux (
    id SERIAL PRIMARY KEY,
    satellite TEXT NOT NULL,
    time TIMESTAMP NOT NULL,
    species TEXT,
    ProtonT1_1 TEXT,
    ProtonT1_1_unc TEXT,
    AlphaT1_1 TEXT, 
    AlphaT1_1_unc TEXT,
    ProtonT1_2 TEXT,
    ProtonT1_2_unc TEXT,
    AlphaT1_2 TEXT, 
    AlphaT1_2_unc TEXT,
    ProtonT1_3 TEXT,
    ProtonT1_3_unc TEXT,
    AlphaT1_3 TEXT, 
    AlphaT1_3_unc TEXT,
    ProtonT1_4 TEXT,
    ProtonT1_4_unc TEXT,
    AlphaT1_4 TEXT, 
    AlphaT1_4_unc TEXT,
    ProtonT1_5 TEXT,
    ProtonT1_5_unc TEXT,
    AlphaT1_5 TEXT, 
    AlphaT1_5_unc TEXT,
    ProtonT1_6 TEXT,
    ProtonT1_6_unc TEXT,
    AlphaT1_6 TEXT, 
    AlphaT1_6_unc TEXT,
    ProtonT2_1 TEXT,
    ProtonT2_1_unc TEXT,
    AlphaT2_1 TEXT, 
    AlphaT2_1_unc TEXT,
    ProtonT2_2 TEXT,
    ProtonT2_2_unc TEXT,
    AlphaT2_2 TEXT, 
    AlphaT2_2_unc TEXT,
    ProtonT3_1 TEXT,
    ProtonT3_1_unc TEXT,
    AlphaT3_1 TEXT, 
    AlphaT3_1_unc TEXT,
    ProtonT3_2 TEXT,
    ProtonT3_2_unc TEXT,
    AlphaT3_2 TEXT, 
    AlphaT3_2_unc TEXT,
    ProtonT3_3 TEXT,
    ProtonT3_3_unc TEXT,
    AlphaT3_3 TEXT, 
    AlphaT3_3_unc TEXT,
    ProtonT3_4 TEXT,
    ProtonT3_4_unc TEXT,
    AlphaT3_4 TEXT, 
    AlphaT3_4_unc TEXT,
    ProtonT3_5 TEXT,
    ProtonT3_5_unc TEXT,
    AlphaT3_5 TEXT, 
    AlphaT3_5_unc TEXT
);