CREATE TABLE particle_flux (
    id SERIAL PRIMARY KEY,
    satellite TEXT NOT NULL,
    time TIMESTAMP NOT NULL,
    species TEXT,
    ProtonT1.1 TEXT,
    ProtonT1.1_unc TEXT,
    AlphaT1.1 TEXT, 
    AlphaT1.1_unc TEXT,
    ProtonT1.2 TEXT,
    ProtonT1.2_unc TEXT,
    AlphaT1.2 TEXT, 
    AlphaT1.2_unc TEXT,
    ProtonT1.3 TEXT,
    ProtonT1.3_unc TEXT,
    AlphaT1.3 TEXT, 
    AlphaT1.3_unc TEXT,
    ProtonT1.4 TEXT,
    ProtonT1.4_unc TEXT,
    AlphaT1.4 TEXT, 
    AlphaT1.4_unc TEXT,
    ProtonT1.5 TEXT,
    ProtonT1.5_unc TEXT,
    AlphaT1.5 TEXT, 
    AlphaT1.5_unc TEXT,
    ProtonT1.6 TEXT,
    ProtonT1.6_unc TEXT,
    AlphaT1.6 TEXT, 
    AlphaT1.6_unc TEXT,
    ProtonT2.1 TEXT,
    ProtonT2.1_unc TEXT,
    AlphaT2.1 TEXT, 
    AlphaT2.1_unc TEXT,
    ProtonT2.2 TEXT,
    ProtonT2.2_unc TEXT,
    AlphaT2.2 TEXT, 
    AlphaT2.2_unc TEXT,
    ProtonT3.1 TEXT,
    ProtonT3.1_unc TEXT,
    AlphaT3.1 TEXT, 
    AlphaT3.1_unc TEXT,
    ProtonT3.2 TEXT,
    ProtonT3.2_unc TEXT,
    AlphaT3.2 TEXT, 
    AlphaT3.2_unc TEXT,
    ProtonT3.3 TEXT,
    ProtonT3.3_unc TEXT,
    AlphaT3.3 TEXT, 
    AlphaT3.3_unc TEXT,
    ProtonT3.4 TEXT,
    ProtonT3.4_unc TEXT,
    AlphaT3.4 TEXT, 
    AlphaT3.4_unc TEXT,
    ProtonT3.5 TEXT,
    ProtonT3.5_unc TEXT,
    AlphaT3.5 TEXT, 
    AlphaT3.5_unc TEXT,
)