CREATE TABLE particle_flux (
    id SERIAL PRIMARY KEY,
    satellite TEXT NOT NULL,
    time TIMESTAMP NOT NULL,
    species TEXT,
    ProtonT1.1,
    ProtonT1.1_unc,
    AlphaT1.1, 
    AlphaT1.1_unc,
    ProtonT1.2,
    ProtonT1.2_unc,
    AlphaT1.2, 
    AlphaT1.2_unc,
    ProtonT1.3,
    ProtonT1.3_unc,
    AlphaT1.3, 
    AlphaT1.3_unc,
    ProtonT1.4,
    ProtonT1.4_unc,
    AlphaT1.4, 
    AlphaT1.4_unc,
    ProtonT1.5,
    ProtonT1.5_unc,
    AlphaT1.5, 
    AlphaT1.5_unc,
    ProtonT1.6,
    ProtonT1.6_unc,
    AlphaT1.6, 
    AlphaT1.6_unc,
    ProtonT2.1,
    ProtonT2.1_unc,
    AlphaT2.1, 
    AlphaT2.1_unc,
    ProtonT2.2,
    ProtonT2.2_unc,
    AlphaT2.2, 
    AlphaT2.2_unc,
    ProtonT3.1,
    ProtonT3.1_unc,
    AlphaT3.1, 
    AlphaT3.1_unc,
    ProtonT3.2,
    ProtonT3.2_unc,
    AlphaT3.2, 
    AlphaT3.2_unc,
    ProtonT3.3,
    ProtonT3.3_unc,
    AlphaT3.3, 
    AlphaT3.3_unc,
    ProtonT3.4,
    ProtonT3.4_unc,
    AlphaT3.4, 
    AlphaT3.4_unc,
    ProtonT3.5,
    ProtonT3.5_unc,
    AlphaT3.5, 
    AlphaT3.5_unc,
)